#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export TERM=xterm-256color
export PATH="/usr/local/heroku/bin:$PATH"

# Load custom
source ~/.zsh/custom.zsh
source ~/.zsh/aliases.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/mark/taivara/shuffle-backend/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/mark/taivara/shuffle-backend/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/mark/taivara/shuffle-backend/node_modules/tabtab/.completions/sls.zsh ]] && . /home/mark/taivara/shuffle-backend/node_modules/tabtab/.completions/sls.zsh